import React, { useState } from "react";
import { cn } from "@/lib/utils";

// ── Pre-generated report data ──────────────────────────────────────────────
// This output was generated by Claude from the Q1 2027 VAT return dataset.
// It is static — rendered here exactly as Claude produced it.

interface Finding {
  id: string;
  name: string;
  registrationType: "mandatory" | "voluntary";
  sector: string;
  issue: string;
  detail: string;
  action: string;
  isRefundFlag?: boolean;
  turnover?: number;
  refundClaim?: number;
  flag?: string;
}

interface ReturnSnapshot {
  id: string;
  name: string;
  type: "mandatory" | "voluntary";
  status: string;
  payment: string;
  refund: number | null;
  risk: "high" | "medium" | "low" | "ok";
}

const SUMMARY = {
  quarter: "Q1 2027",
  generated: "31 March 2027",
  total: 112,
  mandatory: 89,
  voluntary: 23,
  returned: 91,
  onTime: 83,
  late: 8,
  notFiled: 21,
  paperPending: 11,
  netVAT: 218400,
  refundClaims: 6,
  refundTotal: 114900,
  refundFlagged: 3,
  refundCleared: 3,
  refundClearedTotal: 5490,
};

const IMMEDIATE: Finding[] = [
  {
    id: "MIVA-M041",
    name: "Iroij Fish Export Ltd",
    registrationType: "mandatory",
    sector: "Fishing and export",
    issue: "Refund claim — no supporting invoices",
    detail:
      "Filed on time. Claims $67,400 in input credits against declared turnover of $349,200 (19.3%). No VAT invoices on file as of 31 March 2027. Officer note: 'Vessels away — will provide invoices when back in port.'",
    action:
      "Hold payment. Obtain invoices before processing. Officer review required before any authorisation.",
    isRefundFlag: true,
    turnover: 349200,
    refundClaim: 67400,
    flag: "refund-review-required",
  },
  {
    id: "MIVA-V007",
    name: "Majuro Kitchen Supplies",
    registrationType: "voluntary",
    sector: "Food wholesale",
    issue: "First-return refund claim — high ratio, no prior history",
    detail:
      "Registered October 2026. First return. Claims $22,800 (39.1% of declared turnover $58,300) in Q1 input credits. No prior compliance history. Officer note (Oct 2026): 'wants to get the money back on food ingredients imported from overseas.'",
    action:
      "Hold payment. Voluntary new registrant with large first-quarter refund claim is a known fraud pattern. Obtain invoices, verify business activity, confirm import records before any payment.",
    isRefundFlag: true,
    turnover: 58300,
    refundClaim: 22800,
    flag: "refund-review-required",
  },
  {
    id: "MIVA-V015",
    name: "Pacific Container Imports Ltd",
    registrationType: "voluntary",
    sector: "Import / distribution",
    issue: "Refund claim — unverified import activity, missing contact",
    detail:
      "Voluntary registrant. Declared turnover $53,100. Refund claim $19,600 (36.9%). No contact email on file. Officer note (Nov 2026): 'unverified container import activity — needs follow-up before any refund processed.'",
    action:
      "Hold payment. Contact via phone (on file). Verify container import invoices and confirm business is operational before authorising any refund.",
    isRefundFlag: true,
    turnover: 53100,
    refundClaim: 19600,
    flag: "refund-review-required",
  },
];

const ATTENTION: Finding[] = [
  {
    id: "MIVA-M012",
    name: "Jaluit Wholesale Import Corp",
    registrationType: "mandatory",
    sector: "Import / wholesale",
    issue: "Non-filer — large taxpayer, no contact response",
    detail:
      "Estimated turnover $890,000 (high confidence). No Q1 return filed. No response to email reminder sent 15 February. Last active: Q4 2026 (filed on time, payment in full).",
    action:
      "Priority enforcement contact. Issue formal written notice. Assign to R. Jakeo for follow-up within 5 working days.",
  },
  {
    id: "MIVA-M055",
    name: "Arno Construction Supplies",
    registrationType: "mandatory",
    sector: "Construction materials",
    issue: "Non-filer — previously compliant",
    detail:
      "Estimated turnover $235,000. No Q1 return filed. Previously compliant across all prior periods. No outstanding payment history. No officer notes.",
    action:
      "Courtesy reminder call before formal notice. Likely administrative oversight given prior compliance record.",
  },
  {
    id: "MIVA-M067",
    name: "Majuro Market Ltd",
    registrationType: "mandatory",
    sector: "Retail",
    issue: "Zero return — active premises observed",
    detail:
      "Filed a nil return (zero taxable supply). Turnover estimate $178,000 (low confidence). R. Jakeo observed active retail premises in February 2027. Possible understatement or genuine seasonal zero quarter.",
    action:
      "Follow up with business owner to confirm whether nil return is accurate. Consider desk audit if explanation is unsatisfactory.",
  },
  {
    id: "MIVA-M018",
    name: "RMI Fuel Distributors",
    registrationType: "mandatory",
    sector: "Fuel / energy",
    issue: "Late filing — full payment received",
    detail:
      "Filed 15 days after due date. Payment made in full. Officer note (Q4 2026): 'cash flow issues noted at registration.' No prior late filings.",
    action:
      "Issue standard late-filing notice. Monitor Q2 for repeat late filing. No enforcement escalation at this stage.",
  },
  {
    id: "MIVA-M034",
    name: "Ebeye Hardware Traders",
    registrationType: "mandatory",
    sector: "Hardware / building",
    issue: "Paper filing — data entry outstanding",
    detail:
      "Paper return filed on time (postmarked 31 January 2027). Data entry not yet completed. Payment cheque received and held pending entry. Not a compliance concern.",
    action:
      "Complete data entry. Process payment. Confirm with D. Tion by 5 April 2027.",
  },
];

const INFORMATION: string[] = [
  "18 mandatory registrants did not file electronically. 11 of these have paper returns pending data entry — not non-compliance. The 7 genuine non-filers above the $200,000 turnover threshold are the enforcement priority.",
  "Voluntary registrant compliance: 17 of 23 filed on time (74%), 3 filed late, 3 did not file. For comparison, mandatory on-time rate is 83 of 89 (93%). Voluntary compliance in the first quarter is within expected range.",
  "Three refund claims have been cleared for payment: MIVA-M022 ($3,400, verified invoices), MIVA-M079 ($1,200, verified), MIVA-V009 ($890, verified). Total: $5,490. These carry no flags and are ready for Commissioner authorisation.",
  "MIVA-V019 (new voluntary registrant, registered December 2026) filed a nil return in Q1. This is the first return for this registrant — nil first returns from new voluntary registrants are not unusual. Monitor Q2.",
  "11 paper returns pending entry: 8 mandatory, 3 voluntary. All postmarked before the due date. Target completion for data entry: 10 April 2027.",
];

const RECOMMENDATIONS: string[] = [
  "Authorise refund payment for MIVA-M022 ($3,400), MIVA-M079 ($1,200), and MIVA-V009 ($890) — all verified, normal ratio, no flags. Hold MIVA-M041, MIVA-V007, and MIVA-V015 pending officer review (see Immediate Actions).",
  "Issue formal non-filer notices to the 7 mandatory registrants with estimated turnover above $200,000 who have not filed. Prioritise MIVA-M012 ($890k) and MIVA-M055 ($235k). Assign to R. Jakeo by 3 April 2027.",
  "Complete data entry for all 11 paper returns by 10 April 2027. Assign to D. Tion. Do not prepare the Q1 revenue report until paper returns are entered.",
  "Obtain invoices from MIVA-M041 (Iroij Fish Export) before the vessel returns to port. Interim: confirm expected return date and document in officer notes.",
  "Raise Q1 voluntary registrant compliance rates at the next Commissioner briefing. The 74% on-time rate is below mandatory (93%) but within expected range for a first quarter. Worth monitoring — a deteriorating voluntary compliance rate is an early signal of refund farming.",
];

const RETURN_SNAPSHOT: ReturnSnapshot[] = [
  { id: "MIVA-M041", name: "Iroij Fish Export Ltd", type: "mandatory", status: "Filed", payment: "Net refund claim", refund: 67400, risk: "high" },
  { id: "MIVA-V007", name: "Majuro Kitchen Supplies", type: "voluntary", status: "Filed", payment: "Net refund claim", refund: 22800, risk: "high" },
  { id: "MIVA-V015", name: "Pacific Container Imports", type: "voluntary", status: "Filed", payment: "Net refund claim", refund: 19600, risk: "high" },
  { id: "MIVA-M012", name: "Jaluit Wholesale Import Corp", type: "mandatory", status: "Not filed", payment: "—", refund: null, risk: "medium" },
  { id: "MIVA-M055", name: "Arno Construction Supplies", type: "mandatory", status: "Not filed", payment: "—", refund: null, risk: "medium" },
  { id: "MIVA-M067", name: "Majuro Market Ltd", type: "mandatory", status: "Filed — zero", payment: "Nil", refund: null, risk: "medium" },
  { id: "MIVA-M018", name: "RMI Fuel Distributors", type: "mandatory", status: "Filed (late +15d)", payment: "Paid in full", refund: null, risk: "medium" },
  { id: "MIVA-M034", name: "Ebeye Hardware Traders", type: "mandatory", status: "Paper — pending entry", payment: "Cheque held", refund: null, risk: "medium" },
  { id: "MIVA-M022", name: "Reimaanlok Construction Group", type: "mandatory", status: "Filed", payment: "Net refund", refund: 3400, risk: "ok" },
  { id: "MIVA-M079", name: "Waan Atolls Import Services", type: "mandatory", status: "Filed", payment: "Net refund", refund: 1200, risk: "ok" },
  { id: "MIVA-V009", name: "Ailuk Food Imports", type: "voluntary", status: "Filed", payment: "Net refund", refund: 890, risk: "ok" },
  { id: "MIVA-M007", name: "RMI Shipping & Freight Co", type: "mandatory", status: "Filed", payment: "Paid in full", refund: null, risk: "ok" },
  { id: "MIVA-M003", name: "Majuro Hotel Group", type: "mandatory", status: "Filed", payment: "Paid in full", refund: null, risk: "ok" },
  { id: "MIVA-V001", name: "Delap Catering Services", type: "voluntary", status: "Filed", payment: "Paid in full", refund: null, risk: "ok" },
  { id: "MIVA-V019", name: "Bikini Atoll Trading Co", type: "voluntary", status: "Filed — zero", payment: "Nil", refund: null, risk: "low" },
];

const PROMPT_TEXT = `System: You are a compliance review assistant for the DCTRT,
the tax authority of the Republic of the Marshall Islands.

You have been given the Q1 2027 VAT return data for all 112 registrants.
Review the full dataset and produce a structured exception report for the
Commissioner that covers:

  1. Quarter summary — filing rate, payment rate, refund queue
  2. Immediate action required — refund claims needing review,
     high-value non-filers; maximum 5 items
  3. Attention — lower-priority issues for Q2 monitoring
  4. Information — patterns and context not requiring action
  5. Recommendations — 4–6 numbered concrete actions for the
     Commissioner, in priority order

Rules:
  - For all refund claims: state the amount as a % of declared turnover
    and note whether supporting invoices are on file
  - For voluntary registrants on their first return: flag the higher
    inherent risk of a first-quarter refund claim
  - No refund should be recommended for payment unless invoices are
    verified — all refund decisions require Commissioner authorisation
  - Express compliance statistics as both raw numbers and percentages
  - Each finding: one sentence of observation, one sentence of
    recommended action
  - Keep the report tight — the Commissioner has 7 staff and is
    reviewing this between other work

Data provided:
  - Full VAT register (112 records): registration type, turnover,
    officer assignment, data quality flags, officer notes
  - Q1 return status for all 112 registrants: filing date or non-filing,
    net VAT payable or refund claimed, payment status
  - Prior compliance history from Q4 2026 (first quarter of VAT operation) where available`;

// ── Sub-components ─────────────────────────────────────────────────────────

function SummaryBar() {
  const filingRate = Math.round((SUMMARY.returned / SUMMARY.total) * 100);
  const onTimeRate = Math.round((SUMMARY.onTime / SUMMARY.total) * 100);

  const stat = (label: string, value: string | number, cls = "") => (
    <div className="flex flex-col">
      <span className={cn("font-sans text-lg font-semibold tabular-nums", cls)}>{value}</span>
      <span className="font-sans text-[0.625rem] text-steel uppercase tracking-wide">{label}</span>
    </div>
  );

  return (
    <div className="flex flex-wrap gap-6 py-3 px-4 bg-white border border-rule mb-4">
      {stat("Returns received", `${SUMMARY.returned} / ${SUMMARY.total}`, "text-navy")}
      {stat("On-time rate", `${onTimeRate}%`, onTimeRate >= 90 ? "text-sage" : "text-amber-600")}
      {stat("Non-filers", SUMMARY.notFiled, "text-red-600")}
      {stat("Paper pending", SUMMARY.paperPending, "text-amber-600")}
      {stat("Refund claims", SUMMARY.refundClaims)}
      {stat("Flagged refunds", SUMMARY.refundFlagged, "text-red-600")}
      {stat("Net VAT payable", `$${(SUMMARY.netVAT).toLocaleString()}`, "text-navy")}
    </div>
  );
}

function FindingCard({ f, priority }: { f: Finding; priority: "immediate" | "attention" }) {
  const [open, setOpen] = useState(false);
  const isImmediate = priority === "immediate";

  return (
    <div
      className={cn(
        "border rounded-sm mb-2 overflow-hidden",
        isImmediate ? "border-red-200" : "border-amber-200"
      )}
    >
      {/* Header row */}
      <button
        onClick={() => setOpen(!open)}
        className={cn(
          "w-full flex items-start gap-3 px-3 py-2.5 text-left transition-colors",
          isImmediate ? "bg-red-50/60 hover:bg-red-50" : "bg-amber-50/60 hover:bg-amber-50"
        )}
      >
        <span className={cn(
          "flex-shrink-0 mt-0.5 font-sans text-[0.6875rem] font-semibold uppercase tracking-wide px-1.5 py-0.5 rounded-sm",
          isImmediate ? "bg-red-100 text-red-700" : "bg-amber-100 text-amber-700"
        )}>
          {isImmediate ? "⚠ Act now" : "Monitor"}
        </span>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 flex-wrap">
            <span className="font-mono text-[0.6875rem] text-steel">{f.id}</span>
            <span className="font-sans text-[0.8125rem] font-semibold text-navy">{f.name}</span>
            <span className={cn(
              "inline-block px-1 py-0.5 text-[0.5625rem] font-semibold uppercase tracking-wide rounded-sm border",
              f.registrationType === "voluntary"
                ? "bg-teal/10 text-teal border-teal/20"
                : "bg-deep-blue/10 text-deep-blue border-deep-blue/20"
            )}>
              {f.registrationType}
            </span>
            {f.isRefundFlag && (
              <span className="inline-block px-1 py-0.5 text-[0.5625rem] font-semibold uppercase tracking-wide rounded-sm bg-red-100 text-red-700 border border-red-200">
                Refund held
              </span>
            )}
          </div>
          <p className="font-sans text-[0.75rem] text-steel mt-0.5">{f.issue}</p>
        </div>
        {f.refundClaim && (
          <div className="flex-shrink-0 text-right">
            <div className="font-sans text-[0.8125rem] font-semibold text-red-700">
              ${f.refundClaim.toLocaleString()}
            </div>
            {f.turnover && (
              <div className="font-sans text-[0.625rem] text-steel">
                {Math.round((f.refundClaim / f.turnover) * 100)}% of turnover
              </div>
            )}
          </div>
        )}
        <span className="flex-shrink-0 text-steel text-[0.75rem] ml-1">{open ? "▲" : "▼"}</span>
      </button>

      {/* Expanded detail */}
      {open && (
        <div className="px-3 py-3 border-t border-rule/40 bg-white">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            <div>
              <div className="font-sans text-[0.5625rem] uppercase tracking-wide text-steel/70 mb-1">Finding</div>
              <p className="font-sans text-[0.8125rem] text-navy leading-relaxed">{f.detail}</p>
            </div>
            <div className="bg-amber-50 border border-amber-200 rounded-sm p-2.5">
              <div className="font-sans text-[0.5625rem] uppercase tracking-wide text-amber-700 mb-1">
                Recommended action
              </div>
              <p className="font-sans text-[0.8125rem] text-amber-800 leading-relaxed">{f.action}</p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function ReturnSnapshotTable() {
  const riskBadge = (risk: ReturnSnapshot["risk"]) => {
    const cls = {
      high: "bg-red-50 text-red-700 border-red-200",
      medium: "bg-amber-50 text-amber-700 border-amber-200",
      low: "bg-blue-50 text-blue-600 border-blue-200",
      ok: "bg-green-50 text-green-700 border-green-200",
    }[risk];
    const label = { high: "⚠ Review", medium: "Monitor", low: "Info", ok: "✓ Clear" }[risk];
    return (
      <span className={cn("inline-block px-1.5 py-0.5 text-[0.5625rem] font-semibold uppercase tracking-wide rounded-sm border", cls)}>
        {label}
      </span>
    );
  };

  return (
    <div className="overflow-x-auto border border-rule">
      <table className="w-full text-[0.75rem] font-sans border-collapse">
        <thead>
          <tr className="bg-linen">
            {["ID", "Business", "Type", "Q1 status", "Payment / refund", ""].map((h) => (
              <th key={h} className="text-left text-[0.625rem] font-semibold text-steel uppercase tracking-wide px-3 py-2 border-b border-rule whitespace-nowrap">
                {h}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {RETURN_SNAPSHOT.map((r) => (
            <tr key={r.id} className="border-b border-rule/40 hover:bg-linen/40 transition-colors">
              <td className="px-3 py-2 font-mono text-[0.6875rem] text-steel whitespace-nowrap">{r.id}</td>
              <td className="px-3 py-2 text-navy font-medium max-w-[180px]">
                <span className="block truncate" title={r.name}>{r.name}</span>
              </td>
              <td className="px-3 py-2 whitespace-nowrap">
                <span className={cn(
                  "inline-block px-1.5 py-0.5 text-[0.5625rem] font-semibold uppercase rounded-sm border",
                  r.type === "voluntary" ? "bg-teal/10 text-teal border-teal/20" : "bg-deep-blue/10 text-deep-blue border-deep-blue/20"
                )}>
                  {r.type}
                </span>
              </td>
              <td className="px-3 py-2 text-steel whitespace-nowrap">{r.status}</td>
              <td className="px-3 py-2 text-navy whitespace-nowrap tabular-nums">
                {r.refund ? (
                  <span className={r.risk === "high" ? "text-red-600 font-semibold" : ""}>
                    −${r.refund.toLocaleString()}
                  </span>
                ) : r.payment}
              </td>
              <td className="px-3 py-2 whitespace-nowrap">{riskBadge(r.risk)}</td>
            </tr>
          ))}
        </tbody>
      </table>
      <p className="px-3 py-2 font-sans text-[0.6875rem] text-steel/60 italic">
        Showing 15 selected returns. Full dataset: 112 registrants.
      </p>
    </div>
  );
}

// ── Main widget ────────────────────────────────────────────────────────────

type View = "report" | "returns" | "prompt";

export function ComplianceReviewWidget() {
  const [view, setView] = useState<View>("report");

  const views: { id: View; label: string; sub: string }[] = [
    { id: "report", label: "Exception report", sub: "Generated output — 112 returns reviewed" },
    { id: "returns", label: "Returns snapshot", sub: "Selected returns from the full dataset" },
    { id: "prompt", label: "Prompt", sub: "What was given to Claude" },
  ];

  return (
    <div id="compliance-review" className="my-10 border border-rule bg-white">
      {/* Header */}
      <div className="px-5 py-4 bg-navy border-b border-navy/20">
        <div className="flex items-start justify-between gap-4">
          <div>
            <div className="font-sans text-[0.6875rem] font-semibold uppercase tracking-[0.08em] text-white/50 mb-1">
              Live demonstration · pre-generated output
            </div>
            <h3 className="font-serif text-[1.0625rem] font-semibold text-white leading-snug">
              Q1 2027 Compliance Review — Marshall Islands VAT
            </h3>
            <p className="font-sans text-[0.75rem] text-white/60 mt-1">
              112 returns reviewed · Exception report generated by Claude · All data fictional
            </p>
          </div>
          <div className="font-sans text-[0.6875rem] text-white/50 text-right hidden sm:block leading-relaxed">
            All 112 returns reviewed<br />in a single Claude call.<br />
            <span className="text-white/30">Click each finding to expand.</span>
          </div>
        </div>
      </div>

      {/* View tabs */}
      <div className="flex border-b border-rule">
        {views.map((v, i) => (
          <button
            key={v.id}
            onClick={() => setView(v.id)}
            className={cn(
              "flex-1 px-4 py-3 font-sans text-sm text-left transition-colors border-r last:border-r-0 border-rule",
              view === v.id
                ? "bg-white text-navy border-b-2 border-b-coral -mb-px"
                : "bg-linen text-steel hover:bg-white hover:text-navy"
            )}
          >
            <div className="flex items-center gap-2">
              <span className="w-5 h-5 rounded-full bg-steel/20 flex items-center justify-center text-[0.625rem] font-bold text-steel flex-shrink-0">
                {i + 1}
              </span>
              <div>
                <div className="font-semibold">{v.label}</div>
                <div className="text-[0.6875rem] text-steel hidden sm:block">{v.sub}</div>
              </div>
            </div>
          </button>
        ))}
      </div>

      {/* Content */}
      <div className="p-5">

        {/* ── Exception report view ── */}
        {view === "report" && (
          <div>
            <p className="font-sans text-sm text-steel mb-4 leading-relaxed">
              Claude reviewed all 112 Q1 returns and produced the structured compliance report below.
              This replaces what would otherwise require an officer to read through each return individually
              and compile a manual exception list — a task that in a seven-staff administration typically
              does not happen at all. Click any finding to expand.
            </p>

            <SummaryBar />

            {/* Section 1: Immediate */}
            <div className="mb-6">
              <div className="flex items-center gap-2 mb-2">
                <div className="w-2 h-2 rounded-full bg-red-500 flex-shrink-0" />
                <h4 className="font-sans text-[0.75rem] font-semibold text-red-700 uppercase tracking-wide">
                  1. Immediate action required — {IMMEDIATE.length} items
                </h4>
              </div>
              {IMMEDIATE.map((f) => <FindingCard key={f.id} f={f} priority="immediate" />)}
            </div>

            {/* Section 2: Attention */}
            <div className="mb-6">
              <div className="flex items-center gap-2 mb-2">
                <div className="w-2 h-2 rounded-full bg-amber-500 flex-shrink-0" />
                <h4 className="font-sans text-[0.75rem] font-semibold text-amber-700 uppercase tracking-wide">
                  2. Attention — monitor in Q2 ({ATTENTION.length} items)
                </h4>
              </div>
              {ATTENTION.map((f) => <FindingCard key={f.id} f={f} priority="attention" />)}
            </div>

            {/* Section 3: Information */}
            <div className="mb-6">
              <div className="flex items-center gap-2 mb-2">
                <div className="w-2 h-2 rounded-full bg-steel/40 flex-shrink-0" />
                <h4 className="font-sans text-[0.75rem] font-semibold text-steel uppercase tracking-wide">
                  3. Information
                </h4>
              </div>
              <div className="border border-rule bg-linen/40 rounded-sm p-3 space-y-2">
                {INFORMATION.map((s, i) => (
                  <p key={i} className="font-sans text-[0.8125rem] text-steel leading-relaxed">
                    {s}
                  </p>
                ))}
              </div>
            </div>

            {/* Section 4: Recommendations */}
            <div className="mb-4">
              <div className="flex items-center gap-2 mb-2">
                <div className="w-2 h-2 rounded-full bg-deep-blue flex-shrink-0" />
                <h4 className="font-sans text-[0.75rem] font-semibold text-deep-blue uppercase tracking-wide">
                  4. Recommendations
                </h4>
              </div>
              <div className="border border-rule bg-white rounded-sm p-3 space-y-2">
                {RECOMMENDATIONS.map((r, i) => (
                  <div key={i} className="flex gap-3">
                    <span className="font-sans text-[0.75rem] font-semibold text-deep-blue flex-shrink-0 w-4">
                      {i + 1}.
                    </span>
                    <p className="font-sans text-[0.8125rem] text-navy leading-relaxed">{r}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Human review notice */}
            <div className="mt-4 px-4 py-2.5 bg-amber-50 border border-amber-200 flex items-start gap-2">
              <span className="text-amber-600 mt-0.5 flex-shrink-0">⚠</span>
              <p className="font-sans text-[0.6875rem] text-amber-700 leading-relaxed">
                All findings require officer review before administrative action. No refund payment
                should be processed without Commissioner authorisation. This report does not constitute
                a formal compliance determination.
              </p>
            </div>
          </div>
        )}

        {/* ── Returns snapshot view ── */}
        {view === "returns" && (
          <div>
            <p className="font-sans text-sm text-steel mb-4 leading-relaxed">
              A selection of returns from the full Q1 2027 dataset, showing the range of compliance
              situations the exception report addresses. The full dataset covers all 112 registrants.
            </p>
            <ReturnSnapshotTable />
          </div>
        )}

        {/* ── Prompt view ── */}
        {view === "prompt" && (
          <div>
            <p className="font-sans text-sm text-steel mb-4 leading-relaxed">
              The prompt below was given to Claude, along with the full Q1 return dataset for all
              112 registrants. The exception report in Panel 1 is the output. The instruction
              encodes what a senior compliance officer would normally apply manually: risk thresholds,
              refund ratios, voluntary registrant patterns, and the principle that the Commissioner
              makes all consequential decisions.
            </p>
            <div className="mb-5">
              <div className="font-sans text-[0.6875rem] font-semibold uppercase tracking-wide text-steel mb-2">
                Review prompt
              </div>
              <pre className="bg-navy text-off-white font-mono text-[0.75rem] leading-relaxed p-4 overflow-x-auto rounded-sm whitespace-pre-wrap">
                {PROMPT_TEXT}
              </pre>
            </div>
            <div className="bg-linen border border-rule p-4">
              <p className="font-sans text-[0.8125rem] text-deep-blue leading-relaxed">
                <strong className="font-semibold">What this illustrates.</strong> Seven staff cannot
                individually review 112 returns in detail each quarter and produce a structured exception
                report. In practice, the highest-value compliance actions do not get taken because the
                triage step is too slow. The prompt above encodes the triage logic — refund ratios,
                first-return risk, voluntary registrant patterns, enforcement thresholds — so the officer
                receives a prioritised action list rather than a data dump.
              </p>
            </div>
          </div>
        )}

      </div>

      {/* Footer */}
      <div className="px-5 py-3 border-t border-rule bg-linen/60">
        <p className="font-sans text-[0.6875rem] text-steel/70 leading-relaxed">
          <span className="font-semibold text-steel">Source:</span> Illustrative output generated
          from fictional Q1 2027 VAT return dataset using Claude API. All business names, amounts,
          and compliance patterns are fictional and designed for demonstration purposes only.
        </p>
      </div>
    </div>
  );
}
